%YAML:1.0
---
opencv_eigenfaces:
   threshold: 1.7976931348623157e+308
   num_components: 0
   mean: !!opencv-matrix
      rows: 0
      cols: 0
      dt: u
      data: []
   eigenvalues: !!opencv-matrix
      rows: 0
      cols: 0
      dt: u
      data: []
   eigenvectors: !!opencv-matrix
      rows: 0
      cols: 0
      dt: u
      data: []
   projections:
      []
   labels: !!opencv-matrix
      rows: 0
      cols: 0
      dt: u
      data: []
   labelsInfo:
      []
